import Head from 'next/head';
import 'bootstrap/dist/css/bootstrap.min.css';
import styles from '@/styles/Home.module.css';

export default function Home() {
  return (
    <>
      <Head>
        <title>Blog with nextJS</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className='container px-4 pt-5'>
        <h1>Bienvenue sur Code.ID</h1>
        <span>Le blog spécial pour les formations avec Id Formation.</span>
        <div className='row mt-5'></div>
      </div>
    </>
  );
}
